name: Run shfmt on scripts folder

on:
  pull_request:
    branches:
      - main

jobs:
  shfmt-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Shfmt
        uses: mfinelli/setup-shfmt@4f96029d5d3b7e1d2fd0ac5916f01a8d732e71d0 # v4.0.0

      - name: Run shfmt
        run: |
          shfmt -d scripts