name: Run shfmt on scripts folder

on:
  pull_request:
    branches:
      - main

jobs:
  shfmt-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Shfmt
        uses: mfinelli/setup-shfmt@a25fda4c1fe115aec0f85e04126610841bc3141d # v4.0.1

      - name: Run shfmt
        run: |
          shfmt -d scripts